### ISSUE TITLE
Data table: Align resizable columns to PAL pattern

### ISSUE THREAD

**Issue by johanna-koval** [carbon-design-system/ibm-products#1923]
The current behavior of [row size](https://pages.github.ibm.com/wdp-gov/wkc-shared-ui/?path=/story/datagrid--row-size-dropdown) needs a few adjustments and additions to align to the new [Resizable columns Pal pattern](https://pages.github.ibm.com/wdp-gov/wkc-shared-ui/?path=/story/datagrid--row-size-dropdown)

Related Epic:
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1607

Adjustments and additional behaviors

- Resize multiple columns at a time :

- [ ] Hold Shift, and hover over the right side of any column header until a horizontal split cursor appears.

- [ ] To manually define the width that will be applied to all visible columns, drag the column line to set the desired width.

- [ ] To resize all visible columns to fit the content, double-click the column line.

![resizing_2columns](https://user-images.githubusercontent.com/5809654/163623808-8ea76600-7142-4e45-be50-0c6f45e52fe5.gif)

- Resize column to fit its content:

- [ ] Hover over the right side of the column header until a horizontal split cursor appears. Double-click the column line. The column is resized to fit the contents.
![doubleClick](https://user-images.githubusercontent.com/5809654/163623937-7118dbf8-b482-429a-919f-71d3fa8d4f85.gif)

- [x] Display minimum one letter in a column

<img width="541" alt="CleanShot 2022-04-15 at 15 29 57@2x" src="https://user-images.githubusercontent.com/5809654/163623978-4a22713e-5ef8-49af-8523-a348513f897e.png">

- [ ]  Wrap column header titles

![wrappingHeader](https://user-images.githubusercontent.com/5809654/163624168-03443ea7-d707-496b-91ea-a7cc32b0d9e6.gif)

- Accessibility
-Keyboard navigation

- [ ] tab: navigates the user to the different interactive elements

- [ ] space bar: triggers the selected element

- [ ] enter: triggers the selected element

- [ ] left & right arrow keys: resize column left or right

- [ ] Tab order

First interactive element in the body area.
Proceed left to right and top to bottom through the rest of the body elements.
Primary cell
Secondary resize handle
Secondary cell

**Comment by lizisawizard** [comment]
@johanna-koval For the wrapping column header titles, do single word titles like "Name" just behave like before?

**Comment by johanna-koval** [comment]
Single-word headers would truncate to max one visible letter, keeping the cell 16px padding
<img width="518" alt="CleanShot 2022-04-29 at 08 19 50@2x" src="https://user-images.githubusercontent.com/5809654/165952458-a9970365-ceb2-4eef-8f97-031b706b9f63.png">

**Comment by elycheea** [comment]
@Ratheeshrajan do you mind taking a look at this one?

**Comment by mbgower** [comment]
Here are the accessibility considerations I can think of for this.

### Quick research
An admittedly cursory check in the wild did not turn up a lot documentation on keyboard-accessible web-base column resize controls, but I did find a few things.
1. This interesting [prototype example](https://dev.to/madsstoumann/accessible-resizable-table-columns-5eof) that used the `input type="range"`. The nice thing about the built-in keyboard accessibility from input range is that it allows for l/r arrows for fine- and home/end keys for gross-range adjustments. It's extremely flakey in the prototype. You can try out a more stable single width adjustment in this[ example of a side-by-side image compare](https://dev.to/madsstoumann/accessible-image-compare-one-line-of-javascript-3gn4), from the same dev.
2. Someone had a stackoverflow query about [Proper accessibility or ARIA role for a resize handle](https://stackoverflow.com/questions/42981485/proper-accessibility-or-aria-role-for-a-resize-handle), and the voted answer talks about [role=separator](https://www.w3.org/TR/wai-aria/roles#separator) and [aria-orientation=horizontal](https://www.w3.org/TR/wai-aria/states_and_properties#aria-orientation), which I think are valid points. The answer also flags issues with slider role in this context from a screen reader perspective (which is also mentioned in the comments of the first reference.
3. A closed [Microsoft issue](https://github.com/microsoft/fluentui/issues/4947) on column resizable keyboard accessibility that outlines some challenges, especially when tried in a grid (which does not apply in this data table scenario, as far as I can tell).
4. Salesforce has a [demonstration of a single resizable column](https://salesforce-ux.github.io/dnd-a11y-patterns/#/resize?_k=xiwe27) using the range input. They discuss it in detail as the [fourth option in an article on drag and drop](https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09#9ee3).
5. Finally, the Aria Authoring Practices has nothing on resizing in the Table or Grid patterns. However, they do have a [window splitter pattern](https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/) which I believe is quite relevant, including recommended keyboard interaction.

### Investigation on my existing apps
I then spent some time looking at how resizing happens in spreadsheets, including Excel and google sheets. Obviously spreadsheets, like aria grids, have a lot more functionality to think about than a data table, but it's worth pointing out. Nonetheless, it's useful context. All I looked at used a process of selecting a column, then activating its context menu to bring up a numeric input for column size. For instance, in Excel, you select a column with Ctrl+Space, then Shift+F10 to bring up the context menu, select Column width, and then put a value into an input.
<img width="262" alt="Screenshot 2022-11-03 at 6 20 15 AM" src="https://user-images.githubusercontent.com/14298245/199741733-302c04ba-02c9-4e82-a424-63865eda99e2.png">
<img width="228" alt="Screenshot 2022-11-03 at 6 19 43 AM" src="https://user-images.githubusercontent.com/14298245/199741746-882ce0a4-423d-466c-853f-45772fcff6c5.png">

That's probably enough for one comment. I'll talk about considerations in the next comment :)

**Comment by mbgower** [comment]
### Pointer accessibility
Before listing what are a lot of keyboard interaction thoughts, it's important to mention that the following are likely to be mouse considerations in 2023:
- [target size](https://w3c.github.io/wcag/understanding/target-size-minimum.html). WCAG 2.2 is likely to require controls to be at least 24x24 or have at least that much target plus spacing. Google sheets have a funky little rollover effect that fattens the control for resizing to make it easier to hit by pointer. You may not have thought about pointer affordance, but this is a valid consideration.
- [dragging alternative](https://w3c.github.io/wcag/understanding/dragging-movements.html). WCAG 2.2 is also likely to have a requirement that there be a way for _pointer_ users to resize without dragging their mouse. A keyboard option is not sufficient.

**Comment by mbgower** [comment]
### Screen reader

As mentioned by a few folks in the issues cited in my original comment, making something keyboard operable does not necessarily make it screen reader usable. If the role and context aren't conveyed, or the role chosen doesn't make sense for the keyboard interaction, or JAWS doesn't understand that some keys have been 'hijacked' for an unusual purpose, the results can be ugly. As long as it's being thought of and tested for, this is not necessarily a big barrier.

I'll reiterate here that another challenge you have is that the column header behaviour is likely going to be inconsistent across an application. A table may or may not have a 'sort' function. Column headers aren't even normally interactive (don't take focus) where they aren't sortable. I'm assuming not every table's columns are going to be resizable? So we have to signal to all users what a particular table's header function is, and we need to accommodate potentially three interactions (sort, resize, reveal text truncation) into one cell. It's not an insurmountable challenge, but it needs to be thought through.

**Comment by mbgower** [comment]
### Option 2: Incorporate keyboard interaction into the column headers

This is where I think your original plan was. My gut tells me that the menu is easier as a first iteration, but this is potentially workable. Here are the main considerations:
- navigation
- visual affordance
- operation
- conflicts (with scrolling, sorting and screen readers)

#### Navigation
Obviously you have to make the column headers navigable by keyboard. In your demo, a keyboard user cannot currently get to them. The main two options here are to add each resizable column header to the tab order OR make the column row a single tab stop, and allow arrowing between columns.

Since you want to use arrow keys to adjust the column widths, I think the former is simpler. The advantage of the latter is that you don't add a bunch of additional time on task for keyboard users who IMO are not going to want to resize tables as much as they're going to want to read/interact with the data in them. Since sortable columns will have already added the column headers to the tab order, some tables _may_ not have time on task increased.

#### Visual affordance
How is the resizing ability conveyed to users, both mouse users and keyboard users? Carbon already has an unfortunate [non-persistent column sorting challenge](https://github.com/carbon-design-system/carbon/discussions/11119), where unless a table is sorted, one does not _know_ it can be sorted until either discovered by pointer hover exploration or keyboard focus.
Setting aside the pointer considerations, how do I convey to a keyboard user resizing even exists? For sorting, the symbols appear on focus. 
![image](https://user-images.githubusercontent.com/14298245/199764073-fe08ee24-a346-44bd-9958-24911a6dbbf3.png)
A similar tactic could be used for resizing. You'll need to figure out how to convey 'resize' instead of 'reorder'. Examples in the splitter pattern may help with this. You'll also have to make sure having cells that are both sortable and resizable  makes visual sense. (You may want to at least consider a future where you also want to reorder...)

#### Operation and potential conflicts
I'm assuming the proposed left/right arrow and home/end operation happens only with focus on a cell. That sounds workable. The big potential challenge I see at the moment is that **sorting** relies on the cell being activated (with Space/Enter). Activation causes sorting to be toggled between ascending/descending/unsorted. So one header cell transformation involves activation, but it's now going to have some actions that just transform based on other keys. It's not clear to me a keyboard user will understand that. There's not a keyboard conflict per se. I'm just unsure how a user is going to think "The up/down arrows being shown to me _aren't_ telling me to use up and down arrows, but the left and right arrows shown to me _are_ telling me that."

There is also the fact that the arrow keys are normally used to reposition the viewport -- something a keyboard only user may be doing _a lot_ in regard to data in a table, where there could be horizontal scrollbars to show columns of data. The fact there are only conflicts while the column header cells are in focus makes it less of a problem. I think there are also Carbon design recommendations to restrict the number of columns shown?

Finally, the multiple roles on a single cell is going to be a challenge to convey to screen reader users, and handling all the key press events will need to be carefully thought through. I don't want to go into a dissertation on screen reader operation, but especially in the context of a header cell where the text may be obtuse, the user may want to review the words or even characters in the cell to understand what it is saying. They use their arrow keys in combination with other keys to do that. Some implementations of table navigation for screen readers also basically allow them to traverse (non-interactive) cells with arrows keys. So checking the operation during development THEN having some native screen reader users fully test iterations of the experience is going to be pretty important.

**Comment by mbgower** [comment]
### Option 3 Cell actions

I thought I'd mention this potential approach. The user _activates_ a header cell, at which point all the potential functions of the cell are revealed. There are a few ways to provide this. One would be making each cell effectively a menu button.
You could potentially treat your header row as a single complex component. The whole row might only need to take one tab stop, with the user navigating into it to activate different cells.

**Comment by elycheea** [comment]
Opened smaller issues to capture each of these individual tasks. Expecting #3515 and #3516 to be closer to DataSpreadsheet behavior so included those as tasks to investigate further.
