### ISSUE TITLE
Contributors Badge Broken

### ISSUE THREAD

**Issue by jagathgj** [carbon-design-system/ibm-products#2457]
## Contributors Badge Broken

Contributors badge on top of getting started page is broken

> Is this issue related to a specific component?
No

> What browser are you working in?
Chrome

## Steps to reproduce the issue

1. Go to [getting started page](https://carbon-for-ibm-products.netlify.app/?path=/story/overview-getting-started--page)
2. On top you will find the Contributors badge is broken

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/29351394/201260853-73e7f2a4-bf76-4ed4-9fe7-0ce679e12283.png">

**Comment by elycheea** [comment]
So far this looks a little more complex than originally expected. I fixed the Netlify badges for now since those shouldn’t be broken (they were just using old badges).

Will need to look for other options for handling our contributors badges. 🤔 Or we may want a more custom home for our Storybook, similar to what other Storybooks (e.g. Carbon) do.

**Comment by elycheea** [comment]
This was fixed in one of the recent PRs adding new contributors. 🎉
