### ISSUE TITLE
Datagrid design review: Expandable rows

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2502]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Johanna Koval (~@johanna-koval~ @johannasuarez-koval), Sammy Schuckert
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/expandable-rows/usage) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-expandablerow)

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by johanna-koval** [comment]
Most of the Design Guidelines on the PAL are directed to how the content inside the expandable area should be laid out and aligned; in that sense, most of the guidelines are for the dev and designers using this expansion in production. 
As for what the component includes in the storybook, everything looks according to the design. There is just one detail about the left alignment between the header, parent row, and nested content:

In the storybook, both the header and parent cell are aligned to the left, but nested content isn't
![CleanShot 2022-12-20 at 15 58 42@2x](https://user-images.githubusercontent.com/5809654/208765305-06caf2eb-b021-4d33-b711-98bbdc4685fe.png)

In the design, everything is aligned to the left:

<img width="698" alt="CleanShot 2022-12-20 at 16 01 00@2x" src="https://user-images.githubusercontent.com/5809654/208765514-4dbf94a3-05be-41c4-8ba0-bc54ee4dd84a.png">

In Carbon alignment is the same as the one in the PAL guidance even though the coded component doesn't match it:
Design
<img width="692" alt="CleanShot 2022-12-20 at 16 08 54@2x" src="https://user-images.githubusercontent.com/5809654/208766964-1920f412-e5b2-47b2-857f-52e7a8bf16c6.png">


Coded component
![CleanShot 2022-12-20 at 16 01 35@2x](https://user-images.githubusercontent.com/5809654/208765742-05bfdad3-2c5c-43b2-acad-fa4556d11765.png)



The alignment and spacing used for the expansion were intended to be the same as the one defined by Carbon: Content is aligned to the left with 48px spacing padding. Is it possible to match this?

**Comment by davidmenendez** [comment]
regarding the expanded row height- the 96px row height is being set by a configurable option `expandedContentHeight: 96`

and then here's what the row looks like with additional content

<img width="1792" alt="Screenshot 2022-12-21 at 10 42 24 AM" src="https://user-images.githubusercontent.com/6370760/208959159-a1fb960e-4815-4a66-b289-45274fafe8c7.png">

i will work on getting either the storybook or codesandbox updated so that you can test setting your own content

**Comment by sammyschuckert** [comment]
Thanks @davidmenendez! 

I'm wondering, if it might be helpful to include some content in a  2-3 column layout and add controls to the story book for having that content layout float in the different ways as described by the PAL guidance [here](https://pages.github.ibm.com/cdai-design/pal/components/data-table/expandable-rows/usage/#how-to-lay-out-content)? So that designers and developers can get a feel for the various options at their disposal.

**Comment by jagathgj** [comment]
Fixed and Merged it. Hence closing
