### ISSUE TITLE
Datagrid design review: Nested rows

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2505]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Johanna Koval (~@johanna-koval~ @johannasuarez-koval)
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/nested-rows/usage) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-nestedrows)

--- 

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by johanna-koval** [comment]
Hi @davidmenendez, I have done an initial review of the coded expansion compared to the design guidance, and here there a few considerations:

**Expansion indicator**
The expansion line that displays on hover looks great! and display for all levels of nesting. I believe the only adjustment needed is the color style, the color token should be $active-ui (gray 30 in Gray10 theme).
We decided to avoid using blue for these elements since, in general, blue is used to indicate a CTA and in the case of the data grid expansions, we are using blue to indicate a row is selected. 
<img width="500" alt="CleanShot 2022-12-20 at 17 15 03@2x" src="https://user-images.githubusercontent.com/5809654/208777217-ba907519-4081-49c2-9c90-3bd94309898a.png">

**Row divider**
Row dividers are not aligned in the same way as the design. Dividers of a nested row align to the left with the text of the parent row above, similar to how the simple row expansion works 
![CleanShot 2022-12-20 at 17 35 00@2x](https://user-images.githubusercontent.com/5809654/208779927-cdbb7f61-7adf-4bab-bb8c-d33ac0d7ee8e.png)


**Column indentation alignment** 
Indentation should only affect the first column. All the other columns should remain aligned with their respective header
Storybook:
![CleanShot 2022-12-20 at 17 19 44@2x](https://user-images.githubusercontent.com/5809654/208778212-90dd45ba-19fb-4633-8192-e85eb449ffd4.png)

Design :

![CleanShot 2022-12-20 at 17 21 39@2x](https://user-images.githubusercontent.com/5809654/208778296-6b42f688-5961-4396-8d77-6a79681b0d60.png)


Please let me know if there is anything I need to expand more, I'll continue adding comments in this thread if I see anything else

**Comment by elycheea** [comment]
@johannasuarez-koval
