### ISSUE TITLE
Use `Popover` in Datagrid filter flyout and row height settings

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-products#2527]
These are both based on the Carbon disclosure pattern that we can use in Carbon 11. See https://github.com/carbon-design-system/ibm-products/issues/3117#issuecomment-1603149634 for more detail.

https://carbondesignsystem.com/patterns/disclosures-pattern/#settings-and-filter-menus

**Comment by elycheea** [comment]
This is still relevant and should be updated at some point in Datagrid v2. Probably not likely to be a breaking change, in which case we could address this after Filtering extension is released.

**Comment by matthewgallo** [comment]
I will do some more looking into this but the problem when we had this previously was that there was a Popover inside of another Popover which created some issues with the tooltip that shows, `Row height`.

See layout issues below because of the nested Popovers
<img width="334" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/10215203/80d200be-7986-4409-a6e6-3d7494f3d1fe">

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/carbon/pull/14200 should fix the style issues 🎉

**Comment by matthewgallo** [comment]
We have now switched over from ToggleTip to Popover 😅
