### ISSUE TITLE
Expose selectedRows in Datagrid component

### ISSUE THREAD

**Issue by Billzg13** [carbon-design-system/ibm-products#2965]
## What will this achieve?

Enchance datagrid component to return the whole selected row instead of just selected row id for the selected rows.

**Currently datagrid supports** `selectedRowIds: {key: boolean}[]`

**And we were interested in getting something like this** `selectedRows: T[]`

## How will success be measured?

`useDatagrid` hook to expose something like this `selectedRows: T[]`

## Additional information

Package.json
```
"@carbon/charts": "1.6.1",
"@carbon/charts-react": "1.6.1",
"@carbon/ibm-products": "2.0.0-rc.17",
"@carbon/react": "1.19.0",
```

**Comment by elycheea** [comment]
@matthewgallo to follow up on if we’ve already added this functionality.

**Comment by matthewgallo** [comment]
Hey @Billzg13, a few follow up questions for you. You mentioned the `selectedRowIds` property, this is something that is provided to the component in order to have pre-selected rows. You mentioned wanting to have the whole row returned, if you mean via an `onChange` event when a row is selected or de-selected, then that is something we currently support.

Check out the [Selectable row story](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/Datagrid.stories.js#L338) to see an example of `onRowSelect` which returns the whole row.

**Comment by Billzg13** [comment]
Hey @matthewgallo we are looking for a way to have access on all the `selectedRows` not only `onChange` but for example.

1. User selects a couple of rows 
2. User wants to do something with these rows such us delete them or do another api call with them. We would need to have access to the whole object of the each row not just the ids.

**Comment by matthewgallo** [comment]
Thanks for that clarification @Billzg13. Batch action `onClick`s will now return the selected row data and the event. This will be available in the next release.
