### ISSUE TITLE
Refactor empty state to reduce redundancy

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-products#2968]
## What will this achieve?

while working on fixing a style issue on the `Tearsheet` component i noticed that all the other variants of tearsheet are using redundant code. we should look to improve the code quality here by doing something similar to how cards or add select works by implementing a base component that they all use. `EmptyStateContent` is kind of like that, but i think it could be further optimized to be more efficient.

**Comment by davidmenendez** [comment]
after looking at this with fresh eyes i still think that a refactor here would be good, but the way i would do it would cause **breaking changes**.

basically i think that we should step away from the named export pattern `NoTagsEmptyState` `NotFoundEmptyState` etc to a variant pattern similar to the way carbon does with `Button`.

my proposal would look more like `<EmptyState variant='notags' />` the benefit here is that we could drastically cut down on boilerplate code. a base component implementation similar to the way cards work would be nice, but unfortunately storybook makes this a bit difficult by not supporting shared proptypes. the proptypes and comments have to be declared in the export in order to propagate the documentation. because of that every single instance of empty state has to redeclare proptypes and create lots of redundant code.

the only thing that's different between each empty state is the illustration. we can take advantage of `Suspense` and `lazy` from react in order to lazy load all the svg's and then conditionally render the svg without loading all the unnecessary svgs.

something like this could be implemented to use a single file
```
const NoTags = lazy(() => import('./notags.svg'));
const NotFound = lazy(() => import('./notfound.svg'));
...
const Empty = ({ variant }) => (
<div className={`${prefix}-${variant}`>
  <Suspense>
    {variant === 'notags' && <NoTags />}
    {variant === 'notfound' && <NotFound />}
  </Suspense
</div>
)
```

@matthewgallo @lee-chase if you have any opinions on this please feel free to add to the discussion!

**Comment by matthewgallo** [comment]
I really like the approach you've outlined. In the [very initial implementation](https://github.com/carbon-design-system/ibm-products/pull/159/files#diff-c73fc69f5569e7296513bfa0f2b5745e3630f9b36fb76d2174d9661fe9f897c3R42) of `EmptyState`, we had a dynamic `require` to load the correct svgs. If I remember correctly, that worked fine locally but when our package was built there were issues loading the svg because of the dynamic require, not sure if it was webpack related or what.

I think a way we could avoid breaking changes here is by using feature flags. This has been something that has come up over the past week or two and this feels like a good scenario to add this new implementation of EmptyStates behind a feature flag (default behavior remains, unless the new EmptyState is enabled via feature flag).

**Comment by davidmenendez** [comment]
excellent. i don't think i've worked with the feature flags in C4P before, so i'll catch up with y'all to get this implementation going 👍
