### ISSUE TITLE
CreateTearsheet with intro and multiple flows shows the wrong information in the influencer panel

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/ibm-products#2972]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Using this component https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createtearsheet--with-intro-step we found out that having patterns with different amount of steps can cause an issue.

> Is this issue related to a specific component?
Yes

> What did you expect to happen? What happened instead? What would you like to
> see changed?
In a CreateTearsheet with intro when user defines flows with different number of steps going back and forth the flows cause steps duplication in the influencer and the flow itself;
I.e. Having two flows with the following steps:
- Flow 1: Steps A,B,C,D
- Flow 2: Steps A,B,C
Expected result: Selecting the first flow then (without closing the tearsheet) going back to the intro and then selecting the second flow, the influencer should list 3 steps (A,B,C)
Current result: The influencer list 4 steps (A,B,C,C)

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
`"@carbon/ibm-products": "^1.52.0"`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud

## Steps to reproduce the issue
- Open https://codesandbox.io/s/angry-jepsen-d2e81h?file=/src/Example/Example.js in Chrome
- Click on `Open CreateTearsheet`
- Click on `Flow 1` and then `Next`
- Influencer should show steps `A, B, C`
- Click on `Back`
- Click on `Flow 2` and then `Next`
- Influencer should show steps `A1, B2, C3, D4`
- Click on `Back`
- Click on `Flow 1` and then `Next`
- Influencer should show steps  `A, B, C` but instead shows `A, B, C, D4`

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox
Codesandbox:
https://codesandbox.io/s/angry-jepsen-d2e81h?file=/src/Example/Example.js

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Hey @kimbaz, sorry for the delay our team has been focused on our v2 release. I can take a look at this!

**Comment by elycheea** [comment]
@kimbaz We’re wrapped up in a few others tasks at the moment. If you’re able to contribute a fix, that would be the fastest in this case. 🙏

**Comment by elycheea** [comment]
@baraaabdelsalam Would you be interested in looking into this one?

**Comment by IdanAdar** [comment]
Any updates please?

**Comment by davidmenendez** [comment]
@IdanAdar @kimbaz 

hello. i can confirm that i am able to replicate this behavior. for starters i'd like i'd like to state that I believe that when using this pattern it's intended to have the flow or steps established before rending the tearsheet and not after. because of that i don't think that the current implementation of create tearsheet supports dynamically updated steps like in the example. i personally think you may want to rethink your implementation given this limitation.

that being said i will still continue to investigate if this is behavior we can support.

**Comment by davidmenendez** [comment]
so if you look at this [CreateTearsheet](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createtearsheet--with-intro-step) example you'll see how a dynamic flow can be set using the `includeStep` attribute. The storybook code can be found [here](https://github.com/carbon-design-system/ibm-products/blob/f6ae5df043ae6ddd25d75daefccaa7c0d8ed426b/packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepWithIntro.js) and should be what you're looking for.

**Comment by elycheea** [comment]
Based on the investigation from @davidmenendez and @paul-balchin-ibm, it looks like you should be able to address this following the examples provided.

If there’s further discussion on the current behavior of the tearsheets, we are happy to continue in [discussions](https://github.com/carbon-design-system/ibm-products/discussions/3355) since we have been considering a future rewrite to make some functionality easier to use.
