### ISSUE TITLE
Developer review of drag and drop designs

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3490]
- [ ] Review [design guidance](https://pages.github.ibm.com/cdai-design/pal/patterns/drag-and-drop/usage)
- [ ] Create a prototype to help determine what’s possible and realistic
- [ ] Reach out to designer owners to establish short term scope and enhancements

Design maintainers are @carrenelloyd Minji Kim

**Comment by paul-balchin-ibm** [comment]
My two cents.

This article might help concerning any accessibility questions: https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09. It's been a while since I've read it.

This showcase might help concerning drag and drop grids: https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html. Be sure to click on the prev/next links above (hard to notice) to see all the variations.

1. (If this is what you're referring to...) If the browser enforces a design that is outside of our control (i.e. 50% transparency), then there's nothing we can do about that.
2. It's my understanding that "drag and drop" must have (in code) clearly defined draggable objects, and clearly defined containers to receive the one object being dragged. Dropping outside of a container should be the same as "cancel operation".
3. These would be nice booleans, if available, especially for lists (vertical) and tabs (horizontal).
4. See link above re: accessibility.
5. Don't know. But we should be able to override any colours via local SCSS file, right? (Assuming classes are being added/removed consistently to reflect state.)
6. You mentioned `persistent handle icon` above. Do you have an example?
7. See link above re: grids.
8. Provide a wrapper around the library that enforces a `theme` prop?

Also, we don't need to find a single library to do _all_ the possible drag and drop features; we could instead use multiple libraries where each one performs any single task, or small groups of tasks, exceptionally well.

**Comment by elycheea** [comment]
From scrum today, seems like we need some more discussion with design to determine scope before we start implementation. May need to provide both structure and styling — not a drag and drop component. We can provide recommendations on how to hook into `dnd-kit`.

dnd-kit serves styles — can pass obj with styles and choose how they are implemented.

**Comment by elycheea** [comment]
Closing as complete since initial review was completed by @lee-chase — followup and documentation of requirements still to follow.
