### ISSUE TITLE
Update alignment of nested row text

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3559]
Design review feedback from Virginia:
- Alignment/padding of nested rows text should align with the bottom border
- ~Parent and child should get same hover color on hover (to match Carbon)~

_Originally posted by @vsnichols in https://github.com/carbon-design-system/ibm-products/issues/3506#issuecomment-1751271371_
            
```[tasklist]
### Acceptance criteria
- [ ] Update nested rows so that text aligns with the row border without losing header cell padding
- [ ] Verify no regressions in expanded rows
```

**Comment by matthewgallo** [comment]
Hey @vsnichols, just reviewing this behavior here with the Carbon DataTable with row expansion, the row's bottom border also extends past the table. One of the reasons for this is because of the padding the cells/header cells have.

Removing the padding from the header cells will allow for the text to align with the row bottom border but the hover state looks incorrect.


![Image](https://github.com/carbon-design-system/ibm-products/assets/10215203/f8310b11-76ab-46c8-a57f-4c0e5920a0cf)

We could apply some kind of mask to visually shorten the row bottom border for each expanded row. Something like the following:


![Image](https://github.com/carbon-design-system/ibm-products/assets/10215203/4e0666f0-3ffe-4ef3-889a-89047ecbe1b9)
