### ISSUE TITLE
Datagrid[Filtering]: refactor parts of filtering with utility or custom hook

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3589]
## What will this achieve?

There are now parts of the Datagrid filtering code that can be broken out into either a utility or a custom hook to remove code duplication. Specifically some of the contents of `clearSingleFilter` in FilterProvider and `applyFilters` from `useFilters`.

**Comment by elycheea** [comment]
@AlexanderMelox if you’re wrapped up for the moment, we can have @davidmenendez pick this up going forward.

**Comment by matthewgallo** [comment]
This issue was originally opened to review how we can reduce code duplication from the [`clearSingleFilter` function](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js#L55-L88) and the checkbox section of the [`applyFilters` function](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js#L159-L176) in `useFilters`.

**Comment by davidmenendez** [comment]
i've been looking at this extensively and basically i think we should probably just leave this alone for now. i think reusability is less of an issue here and we fundamentally need to rethink how the filtering works. i've tried my best to tidy it up, but i think my initial PR is probably as good as it gets right now. long term we definitely want to rethink this in order to optimize it and improve code quality
