### ISSUE TITLE
Datagrid: Customize columns design review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3663]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: @My-Money29 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage) / [Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story) / [Storybook v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story)

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by matthewgallo** [comment]
@tomermai

**Comment by My-Money29** [comment]
1. Docs - Overview - Coded examples - Both options don't work for me.
2. Tooltip for 'customize columns' icon should be set to Position-Bottom, instead of Position-left.
3. Inconsistent naming - Clicked the"customize columns" icon and a tearsheet labeled "Customize display" popped up.
4. Search - Not working for me. I type but nothing happens.
5. Drag and Drop:
a. works as expected (and I love it!). If I drag a row to the right, it will expand the horizontal scroll. No horizontal scroll should occur.
![ezgif-2-a93ebe0317](https://github.com/carbon-design-system/ibm-products/assets/101175720/4e8c259a-2445-4aa5-8147-b1f1dd4e8a39)
b. Frozen Column labeled "Row index" has a lock next to it. I imagine it cannot be reordered, but I didn't expect that it could be hidden.
c.I mistook the "Column Name" row in the list for an actual column in the list. Perhaps needs to be differentiated differently?
6. Tearsheet's description text - ...These specifications will be saved if you leave and return to the data table" - What's the benefit of communicating this information?  I thought it was obvious that my tweaks would be displayed in the data table, once I click the save button.
7. Perhaps a 'reset column customization settings' button needs to be included within the tearsheet.
8. Expected the escape button to close (cancel) the tearsheet!
9. On Chrome:
a.  from the "docs" page, rendering issue with one of the tables.
![ezgif-2-75e651c7b3](https://github.com/carbon-design-system/ibm-products/assets/101175720/3ad283c7-347f-437f-b24e-fb753983cec8)
b. Pagination doesn't work
![ezgif-2-7141ba86e4](https://github.com/carbon-design-system/ibm-products/assets/101175720/a6766969-88a1-4f08-9615-ba301cbe7ee9)
10. Mobile - Android - 'internet', 'duckduckgo', 'firefox', 'chrome' browsers:
a. The 'refresh', 'download csv', 'customize columns' buttons don't appear.
b. Button in menu are different from desktop: Filter, Export, Settings, Import items, Create. 
* Only the 'Filter' button works (opens a filter by label tearsheet). Clicking apply doesn't close the tearsheet.
* Within the tearsheet, there's a copy action nested on top of the 'Apply' button. When tested found out that it's actually the 'copy to clipboard' button from the Hidden column ids section, below the datatable.
c. On the 'Internet' browser there's a restrictions from taking a screenshot, but not on the rest of the browsers.
11. Keyboard accessibility: Accessing the tearsheet through the keyboard had me tab through the whole table in the background, and only then arriving focusing in the tearsheet.

**Comment by elycheea** [comment]
@My-Money29 Was there a specific browser you were using when you were unable to type in the customize columns search? Did some quick checks in Firefox, Chrome, Safari without issue so far. 👀 

> 6. Tearsheet's description text - ...These specifications will be saved if you leave and return to the data table" - What's the benefit of communicating this information?  I thought it was obvious that my tweaks would be displayed in the data table, once I click the save button.

Part of the design spec, but I’d guess it’s also to help with discoverability since there’s two actions that can be done — reorder and show/hide? Might also be necessary for accessibility purposes so that it’s clearer that there are two functions that can be performed.

> 7. Perhaps a 'reset column customization settings' button needs to be included within the tearsheet.

Could bring this up as a possible enhancement with the design owners. It might have been Marion, but can also be accomplished by canceling changes.

> 11. Keyboard accessibility: Accessing the tearsheet through the keyboard had me tab through the whole table in the background, and only then arriving focusing in the tearsheet.

This is a focus trap issue that should be fixed when we address #3499 (I’m guessing fixes to stacked tearsheets, which need the top tearsheet to take focus, is what broke this ...) 

> 10. Mobile - Android - 'internet', 'duckduckgo', 'firefox', 'chrome' browsers:
a. The 'refresh', 'download csv', 'customize columns' buttons don't appear.
b. Button in menu are different from desktop: Filter, Export, Settings, Import items, Create.
Only the 'Filter' button works (opens a filter by label tearsheet). Clicking apply doesn't close the tearsheet.
c. Within the tearsheet, there's a copy action nested on top of the 'Apply' button. When tested found out that it's actually the 'copy to clipboard' button from the Hidden column ids section, below the datatable.

So this is because our responsive menu is implemented a bit separately from the main toolbar actions — this means it’s the consuming product’s responsibility to update the responsive implementation. If we keep this as is, we could update the menus in for each story but it could also be a bit of extra bloat in our Storybook.
Will let @matthewgallo and @davidmenendez share his thoughts on this for short-term/long-term before we open a follow up issue, but our focus for now it keeping our datagrid as composable as we can going forward. :)

**Comment by My-Money29** [comment]
> @My-Money29 Was there a specific browser you were using when you were unable to type in the customize columns search? Did some quick checks in Firefox, Chrome, Safari without issue so far. 👀

Firefox v.119.0.1. Not sure why, but the search works fine now :|
> 
> > 6. Tearsheet's description text - ...These specifications will be saved if you leave and return to the data table" - What's the benefit of communicating this information?  I thought it was obvious that my tweaks would be displayed in the data table, once I click the save button.
> 
> Part of the design spec, but I’d guess it’s also to help with discoverability since there’s two actions that can be done — reorder and show/hide? Might also be necessary for accessibility purposes so that it’s clearer that there are two functions that can be performed.

Thanks for clearing this out. I do not think it's redundant now.
> 
> > 7. Perhaps a 'reset column customization settings' button needs to be included within the tearsheet.
> 
> Could bring this up as a possible enhancement with the design owners. It might have been Marion, but can also be accomplished by canceling changes. 

+1
> 
> > 11. Keyboard accessibility: Accessing the tearsheet through the keyboard had me tab through the whole table in the background, and only then arriving focusing in the tearsheet.
> 
> This is a focus trap issue that should be fixed when we address #3499 (I’m guessing fixes to stacked tearsheets, which need the top tearsheet to take focus, is what broke this ...)

How do we trap the traps before we get trapped? 🪤 
> 
> > 10. Mobile - Android - 'internet', 'duckduckgo', 'firefox', 'chrome' browsers:
> >     a. The 'refresh', 'download csv', 'customize columns' buttons don't appear.
> >     b. Button in menu are different from desktop: Filter, Export, Settings, Import items, Create.
> >     Only the 'Filter' button works (opens a filter by label tearsheet). Clicking apply doesn't close the tearsheet.
> >     c. Within the tearsheet, there's a copy action nested on top of the 'Apply' button. When tested found out that it's actually the 'copy to clipboard' button from the Hidden column ids section, below the datatable.
> 
> So this is because our responsive menu is implemented a bit separately from the main toolbar actions — this means it’s the consuming product’s responsibility to update the responsive implementation. If we keep this as is, we could update the menus in for each story but it could also be a bit of extra bloat in our Storybook. Will let @matthewgallo and @davidmenendez share his thoughts on this for short-term/long-term before we open a follow up issue, but our focus for now it keeping our datagrid as composable as we can going forward. :)

+1
