### ISSUE TITLE
datagrid does not layout in an ideal manner when using actions and sortable columns

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/ibm-products#3733]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When using actions and sortable columns datagrid is cutting off text when it doesn't need to:

![image](https://github.com/carbon-design-system/ibm-products/assets/63593302/ffb54ec5-c82b-47b4-8992-980597ab0be8)

there is a ton of empty room and the name column doesn't need to be so small by default

## Steps to reproduce the issue

See https://stackblitz.com/edit/github-6w6hhw-flacrm?file=src%2FExample%2FExample.jsx,src%2FExample%2Futils%2FmakeData.jsx

If you uncomment `width: getAutoSizedColumnWidth(data, 'name', 'Name')` it's better, however, I don't think we should need this on every column because it means a full iteration of all the data for each column

`getAutoSizedColumnWidth` also doesn't work when the raw value is not the display value, the date row for instance. The raw value is the timestamp but the display value is an iso string on this repo

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Hey @tkolanko, I was able to take a look at the stack blitz you've provided. This is happening because you've included the `useActionColumn` plugin, along with a column definition for your column actions. But you have not provided any `rowActions` to the `useDatagrid` hook. If you intent to include column actions provide them, if not then remove the `useActionColumn` from your `useDatagrid` hook and also remove the actions column definition.

If you happen to still experience any layout concerns after making these changes, feel free to reopen!

**Comment by tkolanko** [comment]
@matthewgallo that does not appear to be the case https://stackblitz.com/edit/github-6w6hhw-flacrm?file=src%2FExample%2FExample.jsx

I added rowActions and the layout is still off

![image](https://github.com/carbon-design-system/ibm-products/assets/63593302/aa6497ac-ab9d-4812-a51f-1e732bc82605)
