### ISSUE TITLE
Datagrid: return all selected row data together

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3818]
## What will this achieve?

Follow up issue to https://github.com/carbon-design-system/ibm-products/issues/2909, this enhancement would return all of the selected row data similar to how `selectedRowIds` returns an array of selected row ids.

## How will success be measured?

When datagrid is able to return an array of select row data.

**Comment by vnikiten01** [comment]
To add.  All the selected row data across multiple pages should be returned.
Example.  Pagination enabled, table re-renders with subsequent page scroll and user is selecting items.  Selection count should be tracked across pages and returned with this new function.

**Comment by matthewgallo** [comment]
That is correct @vnikiten01, it will return all rows across pages if pagination is included.

**Comment by K-Markopoulos** [comment]
There is a challenge in keeping `selectedRowIds` and `selectedRowData` (assuming that's the name for the proposed state) in sync in case of providing initial selections (`initialState.selectedRowIds`), along with server side pagination.
In this case, the initial selections may include some ids that are not available in the first page of data. Since the Datagrid cannot find the rowData for all the selectedRowIds the size of these objects is not guaranteed to be the same, so they are likely to not be in sync.
```
// Assume:
// Server-side pagination, 2 per page
// Server data: [
//     { id: 1, name: 'Bob' },
//     { id: 2, name: 'Joe' },
//     { id: 3, name: 'Dave' },
//     { id: 4, name: 'Dan' },
//     { id: 5, name: 'Alice' },
// ]
// initialState.selectedRowIds: { 1: true, 5: true },
// initialState.pageSize: 2
// State will look like:
{
    selectedRowIds: { 1: true, 5: true },
    selectedRowData: {
      1: { id: 1, name: 'Bob' }
      // Maybe 2: null?
    }
}
```
In this example, the problem is that "Alice" (id: 5) should be selected, but the Datagrid cannot find the rowData for that selection, until it reaches a page where id: 5 is present and get the rowData from there, therefore `selectedRowData` is missing a selection.

Therefore, it is likely that `selectedRowData` might be missing some selections (or all the selections), which questions its usefulness if it might contain false information and we still need `selectedRowIds` to get the actual selections.

@matthewgallo  Are you aware of this limitation and is there a plan for this?

IMO this problem is a blocker from implementing a logic that returns all of the selected row data. We can probably ignore the initial selections and return the **user selected** row data, the rows that user has manually selected by clicking on the checkbox, but that's something different.
