### ISSUE TITLE
Pageheader is not reliably calculating top offset

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#4427]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

- The page header component is ignoring our UI shell product header as a result of a recent change. This is causing the header to collapse behind the UI shell header rather than under it.
- Last version I could reliably test that had a properly working header was v2.19.2. The next version I could upgrade to was v2.26.0.
- I believe the change https://github.com/carbon-design-system/ibm-products/pull/4068 in v2.24.0 was were the breaking change was introduced.

> Is this issue related to a specific component?

- Pageheader

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- Expect the pageheader to accurately calculate the top offset based on any components above it.
- Currently the pageheader is ignoring a UI shell header component

> What browser are you working in?

- Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

- `"@carbon/ibm-products": "2.26.0",`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4AIOps. Multiple squads are reporting similar behavior using the same Pageheader components.

> Please create a reduced test case in CodeSandbox
>
- https://codesandbox.io/p/devbox/frosty-hoover-d2r9md?file=%2Fsrc%2FExample%2F_example.scss%3A12%2C27

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
This code sandbox also demonstrates the issue. Thanks @richardpilot!
https://codesandbox.io/p/live/c0c44383-6add-4fe8-b1e4-1ef8ee52c412?file=%2Findex.html

**Comment by richardpilot** [comment]
Updated sandbox:
https://codesandbox.io/p/devbox/thirsty-nash-d62645

**Comment by xmannyxfreshx1** [comment]
@matthewgallo I've made the sandbox public [Pageheader not collapsing, as expected, under Carbon product header](https://codesandbox.io/p/devbox/frosty-hoover-d2r9md?file=%2Fsrc%2FExample%2F_example.scss%3A12%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsz11noc00073b88jwg45tsq%2522%252C%2522sizes%2522%253A%255B74.16666666666667%252C25.83333333333333%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsz11noc00023b885bw07wl3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsz11noc00043b88639aiaxr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsz11noc00063b884qnw5fbh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.78212772070972%252C57.21787227929028%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsz11noc00023b885bw07wl3%2522%253A%257B%2522id%2522%253A%2522clsz11noc00023b885bw07wl3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsz1nm2900023b89kxokrwke%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A55%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A55%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FExample%252FExample.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsz2s4rb00023b8achtwzkk0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FExample%252F_example.scss%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clt3hbbhl00023b8a1vb07x3i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A26%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A26%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsz2s4rb00023b8achtwzkk0%2522%257D%252C%2522clsz11noc00063b884qnw5fbh%2522%253A%257B%2522id%2522%253A%2522clsz11noc00063b884qnw5fbh%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsz2rwel00xk3b89plkp3cun%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsz2rwel00xk3b89plkp3cun%2522%257D%252C%2522clsz11noc00043b88639aiaxr%2522%253A%257B%2522id%2522%253A%2522clsz11noc00043b88639aiaxr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsz11noc00033b883lgu8nzw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsz11noc00033b883lgu8nzw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A17.394526795895104%257D)

**Comment by davidmenendez** [comment]
@richardpilot @xmannyxfreshx1 thanks for opening this issue. sorry this took so long to get to.

i've been able to solve this problem with making some adjustments to the implementation. namely by making two changes to the css

```
.App { // NEW
  height: 100vh;
  overflow: hidden;
}

.main--content {
  height: calc(100% - #{$spacing-09});
  margin-top: $spacing-09;
  overflow-y: auto; // NEW
}
```

in order to get everything to calculate correctly the div that wraps the `PageHeader` and `Header` (in this case `App`) needs to have a height and overflow set. then adding the overflow control to the content. if you look at this [sandbox](https://codesandbox.io/p/devbox/laughing-brook-mdcgcs) you'll be able to see how it should be implemented.

i apologize if this isn't exactly the most intuitive solution. after looking more at this component i think there's some room for improvement that would improve some quality of life like not having to implement all these heights and overflows. the current storybook implementation doesn't exactly demonstrate this extra required boilerplate.

i'm going to go ahead and close this for now. if you have any other questions please feel free to reach out or re-open this issue.

**Comment by richardpilot** [comment]
Unfortunately that solution doesn't work. The only reason it works for the sample is because it has explicit heights set. Remove those and let the content naturally overflow and the content no longer scrolls because you explicitly set the overflow to hidden.

https://codesandbox.io/p/devbox/strange-morse-k7g86x?file=%2Fsrc%2FExample%2FExample.jsx%3A66%2C17&workspaceId=7bd97f32-1182-43fb-914c-3018a28d33e1

**Comment by richardpilot** [comment]
@davidmenendez Looks like the headerOffset check is wrong. It only triggered if the `offsetTopMeasuringRef` was at the top (i.e. 0) which has no effect and is the opposite behaviour that you would need in an offset checker. 

I've inverted the check so that it works when there's an actual offset. The storybook still works with your boilerplate adjustments but now it also works for the standard Carbon Header approach
