### ISSUE TITLE
Always display action buttons on Datagrid

### ISSUE THREAD

**Issue by BenceLovas** [carbon-design-system/ibm-products#4474]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

Our team is using the Datagrid component, and we would like to display the action buttons at the end of the rows (instead of the overflow menu).

![image](https://github.com/carbon-design-system/ibm-products/assets/27259065/7b2bc2f7-b9ff-426d-9708-0407b1d2cb71)

We've found the documentation for it and it looks promising, our only concern is that these buttons only show up when you hover over the row. So my questions are:
- Is there any standard way (like a property or some config object) to always display these buttons?
- If not, is this something you would add to the library later, or is there a reasoning behind the buttons only show on hover?

**Comment by elycheea** [comment]
@vsnichols and @marion-bruells may be able to share some context about this particular design decision.

**Comment by marion-bruells** [comment]
We recommend the following:
Show action buttons persistently only if the user is being encouraged to click them. Otherwise, action buttons should be always visible on hover to discourage use and de-clutter content that would otherwise become redundant.
Icons on hover reduce the cognitive load (especially in complex tables) and also discourage use of destructive actions. For example: When a table has rows with actions that remove (destructively), delete, disconnect, or destroy the object being acted upon, or if it may cripple the work in another system. 
![image](https://github.com/carbon-design-system/ibm-products/assets/51152537/32b8086c-4d7e-4ba9-9f30-20d083315f86)

So in your case I recommend to show the icons on hover only. See also guidance [here](https://pages.github.ibm.com/cdai-design/pal/components/data-table/row-action-buttons/usage)

If you use an overflow menu (in case you have more than 2 actions), you should show it always persistently by default. Overflow menus on hover are hard to discover due to the low visual contrast (compared to other icons.)

**Comment by BenceLovas** [comment]
We've had complaints from our users that they had a hard time figuring out where the action buttons were when those were in the overflow menu. (My assumption is this specific user group is not digitally native.) So, that's why we were wondering how they would respond if there is nothing displayed at the first place.
Personally I fully understand your reasoning behind de-cluttering and reducing the cognitive load. 
Thanks for the answers!
