### ISSUE TITLE
Unresolved fonts with @carbon/ibm-products 2.X

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/ibm-products#4616]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?
Since we moved to @carbon/ibm-products 2.X we notice a large amount of unresolved font request. 
They get bundled with webpack but css keeps trying to resolve them from the root of the application (failing since we assigned a specific folder for static content.)
Is there a specific config we can use to fix the resolving issue?
(Not sure what those fonts are used for though since the components look good even when they are constantly unresolved)

## Relevant information

We use webpack for bundling and latest version of @carbon/ibm-products 2.X
Please note that this does not happen with @carbon/ibm-products 1.X

**Comment by kimbaz** [comment]
It seems to be related to https://webpack.js.org/loaders/sass-loader/#problems-with-url

**Comment by elycheea** [comment]
@kimbaz Can you share a reproduction so we can investigate this further? Thank you!

**Comment by tay1orjones** [comment]
The `$font-path` config variable can be used to [reconfigure the beginning of the urls](https://github.com/carbon-design-system/carbon/blob/36685a0be5e62db11a60d938c76b1c49a402c99a/packages/styles/scss/fonts/_src.scss#L144-L148) to what matches your build output.

We do this in our sandboxes because they use vite which doesn't require the use of the `~` that is included in the [default](https://github.com/carbon-design-system/carbon/blob/539fc8f1b33a88083260b6b687ca510c09134700/packages/styles/scss/_config.scss#L40-L44) - here's an [example](https://stackblitz.com/github/carbon-design-system/sandboxes/tree/main/react/latest/react-18-vite?file=src%2Findex.scss)

> (Not sure what those fonts are used for though since the components look good even when they are constantly unresolved)

That might be because local font files are used as a fallback.

**Comment by kimbaz** [comment]
We were able to fix it using this webpack configuration:
```js
const loader = [{
  test: /\.(woff|woff2|ttf|eot)/,
  type: 'asset/resource',
  generator: {
    filename: 'fonts/[contenthash][ext]',
    publicPath: `/our_app/${STATIC_PATH}/`
  }
}];
```
