### ISSUE TITLE
PageHeader breadcrumb tooltip displays underneath Carbon UI shell header

### ISSUE THREAD

**Issue by modean** [carbon-design-system/ibm-products#4800]
## What package(s) are you using?

```
"@carbon/colors": "11.21.0",
"@carbon/ibm-products": "2.34.0",
"@carbon/layout": "11.21.0",
"@carbon/react": "1.54.0",
"@carbon/styles": "1.54.0",
"@carbon/themes": "11.34.0",
"@carbon/type": "11.26.0",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-router-dom": "6.22.3"
```

## Detailed description

> Describe in detail the issue you're having.

The `PagerHeader` component provides a breadcrumb trail that is supposed to be using an ellipsis for situation where the browser real estate is narrow and thus the breadcrumb can't be displayed.

In such situation the ellipsis is accompanied by a tooltip. The tooltip unfortunately opens using the position `top` and thus it opens underneath the Carbon UI shell `<header />`. This contradicts the added value of the tooltip.

> Is this issue related to a specific component?

Yes it is related to the `PageHeader` component combined with the Carbon UI shell and there `HeaderContainer`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I did expect the tooltip to be visually rendered in a way where it can be read. For instance under the ellipsis and not atop of the ellipsis.

> What browser are you working in?

Chrome 123.0.6312.105 (Official Build) (arm64)
Firefox 124.0.2 (64-bit)

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "2.34.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

n/a

## Steps to reproduce the issue

1. Create a Carbon UI shell sample that makes use of the `HeaderContainer` component.
2. Create a `PageHeader` component that has a breadcrumb
3. Resize the browser window, so that it renders certain breadcrumb trail elements as an ellipsis.
4. Hover over the ellipsis to trigger the tooltip to be displayed.

## Additional information

https://github.com/carbon-design-system/ibm-products/assets/659775/b2bacd7a-c87b-4162-8a15-d79044f4fe4e

**Comment by modean** [comment]
Note that the Carbon `<header />` has a `z-index` of `8000` where the `<SidePanel />` has a `z-index` of `9000`.

**Comment by makafsal** [comment]
@modean @elycheea - This issue is related to the `OverflowMenu` component from the Carbon. In the Breadcrumb component, we are using the OverflowMenu component to list hidden breadcrumb items like this:

https://github.com/carbon-design-system/ibm-products/assets/9197089/414522e1-ae66-4edf-900b-29bb2fe25c0b

Code:
`packages/ibm-products/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js`
![image](https://github.com/carbon-design-system/ibm-products/assets/9197089/017f260f-be3a-4aad-9fd3-0a823a0c4b2e)

Similarly, I've checked the Carbon storybook to observe the `OverflowMenu` behaviour, there also observed the same issue:

https://github.com/carbon-design-system/ibm-products/assets/9197089/3c95607a-31fc-412e-b285-ad9703ab382b
