### ISSUE TITLE
Enhancement proposal: ability to add our own icons with links in for Notifications in NotificationsPanel

### ISSUE THREAD

**Issue by a-roberts** [carbon-design-system/ibm-products#4926]
## What will this achieve?

We'd like to provide our own icons with Notifications based on, say, a category that could be provided.

More info around custom sorting is under https://github.com/carbon-design-system/ibm-products/issues/4925 and the mention of categories which is relevant here.

An example set of different icons one might want to use would be as follows (regarding Critical, Major, Minor, Warning):

<img width="30" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/12814972/25e238b7-0fc5-4bec-8995-38b54495d296">

I think we'd want the ability to provide, say, a mapping of categories to images, through props. Perhaps having categories is a separate issue (outside of custom sorting).

**Comment by elycheea** [comment]
@a-roberts thanks for opening this! After some discussion, we don’t think we’ll be taking this on currently since this is an area where we’re hoping to create more consistency at the moment.

We are working on alignment between the status icons and status indicators between Carbon for IBM Products and Carbon core. https://github.com/carbon-design-system/carbon/issues/16690
