### ISSUE TITLE
[Datagrids]: Add checkbox as a supported inlineEditType

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5302]
### The problem

Design calls for checkbox

![Screenshot 2024-05-21 at 8 41 00 AM](https://github.com/carbon-design-system/ibm-products/assets/10100397/aa786f05-1af2-43f7-96a1-a5d4afbb0c51)

### The solution

Need checkbox to be supported, right now I only see text, number, selection, and date as supported options

### Owner/main maintainer(s)

IBM

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
@AustinGitHub Hey! Thanks for opening this one.
Could you (or your designers) provide us some more information about the use case? Does the dropdown not work here? You can also have your designers reach out for questions on [#ibmproducts-pal](https://ibm.enterprise.slack.com/archives/CQGR0HC05).

**Comment by AustinGitHub** [comment]
Sure

**Comment by jjennings7** [comment]
Hi @elycheea! The dropdown doesn't work well here because the check box is more like a toggle or boolean. In the below example, that table row can be designated as a key, or nullable. We technically could change it to a dropdown, but that would be a poor user experience: User would have to click on the cell to open the dropdown with true or false options in both of these. It's an extra click each time someone has to change it, and when you have a large table the true/false text is a lot less scannable than the simple checkbox is. 

Also, [according to Carbon](https://carbondesignsystem.com/components/dropdown/usage#when-not-to-use) and best UX practices in general for dropdowns, we should not use a dropdown when there are only 2 choices.

![Screenshot 2024-05-22 at 8 59 51 AM](https://github.com/carbon-design-system/ibm-products/assets/48838320/45d84614-2722-4e23-bde9-5dc113af9e53)
