### ISSUE TITLE
Draft a clear contribution process for Workgroups in boxnote

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5480]
Recently we've seen workgroups struggle to understand the contribution process. While the new website is being built, we want to get out a boxnote of this process that we can share with workgroups immediately. 

Pain points:
- The current site several pages dedicated to a 'framework'. Users might be expecting to find a 'process' instead. 
- There is no quick summary of the process. Users have to go through 4 tabs with deep content. 
- Sometimes a contribution can picking up a pre-defined piece of work and other times it is a large effort from a work group. It's not clear that there are 2 diverging paths. 
- Folks with prior workgroup experience might be going on old assumptions. I.e. that they can self draft and publish without any triaging or reviewing process.
- Since our triaging and reviewing process has changed internally, we need to document this for ourselves and clarify with our community
- Workgroups might not know a piece of work is missing. We need to publish a definition of done and templates/processes to achieve this. For example, following docs and image production guidelines. 
- Workgroups might not know how to scope and project management. We can provide improved support for this.

**Comment by carrenelloyd** [comment]
Now that we've merged teams (core + Products) the delivery process fundamentally changed to how workgroups operate currently, we have not communicated expectations to contributors.

**Comment by carrenelloyd** [comment]
After Step 4 on the Iterate tab https://pages.github.ibm.com/cdai-design/pal/contributing/contribution-framework/iterate

Step 5
Publishing 

We made some minor changes when publishing new documentation to the Carbon for IBM Products PAL website.  

After the DSIT playback, incorporate any feedback and update your work accordingly. A Carbon for IBM Product PAL maintainer <link to Contacts page> will review your work during our next sprint (two weeks long) and may have additional feedback and questions that may not have been immediately evident during the DSIT playback. 


Maintainer review

After you receive feedback from a Carbon for IBM Products maintainer, it's time to mock up the Gatsby website documentation in Figma utilizing the Gatsby theme styles and components <Gatsby Figma link>
Review your work for typos, or grammatical and styling errors, including using the correct image aspect ratios. <Do we want to provide an image example of Do's/Don't's?>


PR submission

After we triage and align the work with our spirits, the Carbon team will submit the PR on your behalf. Due to the volume of work we receive from our community, this could take a few weeks.

**Comment by matthewgallo** [comment]
@aubrey-oneal and/or @oliviaflory could you give this a review for @carrenelloyd?

**Comment by aubrey-oneal** [comment]
I think it reads well, Carrie! Could you just add in that that they should follow the docs templates provided? They can choose to write this in [MDX](https://carbondesignsystem.com/contributing/documentation/) or in [Figma](https://www.figma.com/design/XQqHxu38CiY3Vx1iHdafIa/Image-production-guidelines?node-id=2651-218&t=8dbKakT0lQtlR6U7-0)?
