### ISSUE TITLE
Extra column is displayed last at DataGrid

### ISSUE THREAD

**Issue by shidunce** [carbon-design-system/ibm-products#5677]
### Package

Carbon for IBM Products

### Description

We are using DataGrid component. When we configure it to display set of columns all of them are displayed, but in addition some "ghost" column appears on the right. It has no name and values, but it is displayed.
Any legit way of getting rid of it?
Looks like bug.

https://v1-ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-datagrid--basic-usage

![image](https://github.com/user-attachments/assets/8b22534a-f8d2-4ea8-9a6f-22b9c4d2d565)

### Component(s) impacted

See above.

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

-

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM Turbonomic

### CodeSandbox or Stackblitz example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
@shidunce Thanks for reaching out. This was intentional for ease of resizing but after a few reports we did introduce a fix for this in our v2 package.
https://github.com/carbon-design-system/ibm-products/pull/5377

You’re welcome to create a PR to contribute this back for the v1 branch as well, but with [Carbon 10 end of support](https://ibm.slack.com/archives/CJ35H36MP/p1721070510148849) in September 30, our team will be focused on other priorities for the time being.
