### ISSUE TITLE
TagSet styling colors

### ISSUE THREAD

**Issue by csamarchi** [carbon-design-system/ibm-products#5836]
### Package

Carbon for IBM Products

### Description

Prior to carbon11, we overrode the `TagSet` styles to change background and text color. However, it's not cooperating with the color themes in carbon11.

### Component(s) impacted

As is:

![Screenshot 2024-08-08 at 11 04 18 AM](https://github.com/user-attachments/assets/78478aa3-3c17-43df-9572-f7c1f43529dd)
![Screenshot 2024-08-08 at 11 04 25 AM](https://github.com/user-attachments/assets/527f8799-a681-4736-a717-cbd283ce169b)

With the overriding styles (using `theme.$text-primary`):

![Screenshot 2024-08-08 at 10 54 48 AM](https://github.com/user-attachments/assets/a94299e9-22ba-4980-b9e4-440287714be2)
![Screenshot 2024-08-08 at 10 54 57 AM](https://github.com/user-attachments/assets/94e04230-1965-4dbc-ade5-0e88ad0f2088)

What we want:

![Screenshot 2024-08-08 at 11 17 30 AM](https://github.com/user-attachments/assets/fd6e68cd-684c-4948-bdcf-cd263c683b1b)
![Screenshot 2024-08-08 at 11 18 28 AM](https://github.com/user-attachments/assets/8f0cba46-dae7-4ce2-8ac7-f31c1884da1f)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.43.1

### Suggested Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Product/offering

Projects-ui

### CodeSandbox or Stackblitz example

https://github.ibm.com/epx/projects-ui/pull/2275

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @csamarchi 

Theming is a bit different in v11 compared to v10.

Because the tooltip is a high contrast color compared to the rest of the ui, you need to use `$text-inverse` instead of `$text-primary` to get the color you had in v10.


![Image](https://github.com/user-attachments/assets/532dd49d-ddbc-4ab5-83a2-216361d7e141)



I will also say the expected behavior for tag set is to see the different colored tags in the popover (not plain text like you are showing)

![Image](https://github.com/user-attachments/assets/5443c4ab-9cf5-4d7d-846a-49e208ffccd2)

**Comment by csamarchi** [comment]
Ok so giving it theme.$text-inverse fixed the issues. Thank you!
