### ISSUE TITLE
[Datagrid]: Virtual scrolling container div has zero width

### ISSUE THREAD

**Issue by holmansze** [carbon-design-system/ibm-products#6134]
### Package

Carbon for IBM Products

### Description

After moving up from `2.47.0` to `2.50.0`, when rendering Datagrid with virtual scrolling (`useInfiniteScroll`), the Datagrid is sometimes invisible.

<img width="1714" alt="image" src="https://github.com/user-attachments/assets/1d7e0742-fa47-4f93-918a-76fcab617bb0">

When inspecting the DOM, I saw that the virtual scrolling container div (with class `c4p--datagrid__virtual-scrollbar`) has `width: 0px`, unchecking it will reveal the table.

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/1f40fc53-0a02-4c7d-8a92-6d6b661cbf09">

This is a regression. It didn't happen in `2.47.0`.

In `2.47.0`, there is no `width: 0px`:
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/08f67331-e894-4607-a2c0-2299c4c9d7f9">

### Component(s) impacted

Datagrid that uses `useInfiniteScroll`.

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.50.0

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM Cloud Projects

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by devadula-nandan** [comment]
Hi @holmansze ,

[this](https://github.com/carbon-design-system/ibm-products/commit/73a98242150e421a7c414bf7743f453a2234caba#diff-b724a4b3a378eb81dab75fe56fa4ba0995568193d6bbd65a97a78bf4f91b341bR106) might be the cause of the regression, but not completely sure.

however, i believe one of my recent [pr](https://github.com/carbon-design-system/ibm-products/pull/6135) would fix that.
do you have a reproducible case, so we could test it?

**Comment by crichtonibm** [comment]
I was going to open a new issue, but I believe this is a different consequence from the same recent change:   

https://github.com/carbon-design-system/ibm-products/commit/73a98242150e421a7c414bf7743f453a2234caba

I also was fine at 2.47.0 ... after, I get NO width applied anywhere, and so I get no scrollbar. It is all sized to 100% by inheritance. 

Referenced change to  DataVirtualBody moved from always applying a changed clientWidth to the table body, to introducing two separate isomorphicEffects:

```javascript
  useIsomorphicEffect(function () {
    if (headWrapRef.current && headWrapRef.current.style) {
      var _gridRef$current;
      headWrapRef.current.style.width = "".concat(gridRef === null || gridRef === void 0 || (_gridRef$current = gridRef.current) === null || _gridRef$current === void 0 ? void 0 : _gridRef$current.clientWidth, "px");
    }
  }, [headWrapRef, gridRef]);
  useIsomorphicEffect(function () {
    if (testRef !== null && testRef !== void 0 && testRef.current && testRef.current.style) {
      var _gridRef$current2;
      testRef.current.style.width = "".concat(gridRef === null || gridRef === void 0 || (_gridRef$current2 = gridRef.current) === null || _gridRef$current2 === void 0 ? void 0 : _gridRef$current2.clientWidth, "px");
    }
  }, [testRef, gridRef]);
``` 

In my case, gridRef is set, but gridRef.current is not. It makes it into the effect once for the header-wrap and once for the virtual scrollbar.   Since current is not set, I get NO width. I imagine for @holmansze it IS set, but the clientWidth is 0, and so it gets stuck there. 

Either the clientWidth needs to be set on those individual components always, or the 'watcher arrays' on the effects should be referencing the actual elements and the target clientWidth ... something like:  [testRef?.current, gridRef?.current?.clientWidth]

**Comment by davidmenendez** [comment]
@holmansze @crichtonibm could one of your provide a republication of this behavior in a code sandbox, stackblitz, etc? that would help us in identifying and debugging this. thanks!

**Comment by matthewgallo** [comment]
Hey @holmansze, @devadula-nandan's [PR](https://github.com/carbon-design-system/ibm-products/pull/6135) should be included in our release candidate which will be published later today.
