### ISSUE TITLE
Condition Builder: initial state getting reset on re-rendering

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/ibm-products#6457]
This issue was highlighted in our [support channel](https://ibm-studios.slack.com/archives/C013ZTX0N6B/p1729773104440639).

Currently initial state is respected during first render only, need to support re-renders as well.

https://github.com/user-attachments/assets/c07e8946-2a50-4308-83b8-baf06c9bdded

**Comment by ibmwatsoncode** [comment]
Hi @amal-k-joy,  I am trying to use conditionBuilder with initialState Hierarchical property. I have set enabledDefault to true but still on loading initialState is not showing up and only ‘Add Condition + ’ is visible. Ideally, on loading the  object passed in initialState should display instead of “Add Condition +’.
Pls, find the code sample in the below stackblitz URL.
https://stackblitz.com/edit/github-kc5f6a?file=src%2FExample%2FExample.jsx,src%2FExample%2F_example.scss,node_modules%2F%40carbon%2Ficons-react%2Flib%2Fgenerated%2Fbucket-7.d.ts
